name = "anilist-fisher"
main = "src/worker.js"
compatibility_date = "2025-01-01"
workers_dev = true
minify = true
[triggers]
crons = ["0 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "neon-anime-db"
database_id = "3ee54e19-03cb-45ce-8877-a540e1d78adf"

[observability]
enabled = true
