name = "anilist-fisher"
main = "src/worker.js"
compatibility_date = "2024-12-01"
workers_dev = true
minify = true

[[d1_databases]]
binding = "DB"
database_name = "neon-anime-db"
database_id = "3ee54e19-03cb-45ce-8877-a540e1d78adf"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "9429d1b5b13343f58ee3275327241ccd"

[vars]
ALLOWED_ORIGIN = "https://neonanime.pages.dev"

[observability]
enabled = true
